### ISSUE TITLE
Cannot read property <playerId> of undefined (playerIdsIndexed)

### ISSUE THREAD

**Issue by tarolling** [devlemire/6mans-JS#10]
I'm having trouble with the enterQueue command in that it keeps telling me that playerIdsIndexed is undefined. The fs.readFile doesn't affect anything here. The first image is of the enterQueue file (not all of it) where the error occurs, and the next two images are of my managePlayerQueues file. Let me know if you need any other screenshots so I can fix this. If you see differences between the code, it's because I am attempting to make a Rock Paper Scissors bot so I stripped some things I didn't need out of my code, such as voting and the creation of voice channels.
![image](https://user-images.githubusercontent.com/34352544/118515954-7d4a4d00-b6fb-11eb-961a-fb5a71a9e471.png)
![image](https://user-images.githubusercontent.com/34352544/118516168-b1be0900-b6fb-11eb-8713-6c75b5e441a4.png)
![image](https://user-images.githubusercontent.com/34352544/118516234-bf738e80-b6fb-11eb-8a77-6a336d47ef11.png)

**Comment by devlemire** [comment]
Your first screenshot, I'll refer to it as file `X`. You basically need to find the file(s) that import file `X` and call the function it exports. It should be called with the Discord event object and the queue object. You can add a console.log of `queue` in your file to see what its value. 

Is the entire queue undefined? That tells you it's not being passed into the function, which is why queue.playerIdsIndexed is undefined.

**Comment by devlemire** [comment]
https://github.com/devlemire/6mans-JS/blob/master/onHandlers/message.js#L72

You can use this link to see how this API finds the player's queue and then passes it into all the different actions. Finding the `queue` object before calling the function (enterQueue.js) is the vital piece.

**Comment by tarolling** [comment]
Ok, so I found where `queue` is being passed into the enterQueue function in the first screenshot, which is my onHandlers/message.js. The entire queue is being defined, however, as shown in the second and third pictures where the console prints out the queue (the 2nd and 3rd are from enterQueue.js). The playerIdsIndexed object is empty, would it have to do anything with that?
![image](https://user-images.githubusercontent.com/34352544/118668145-3a02e380-b7ba-11eb-8689-af7421f72b74.png)
![image](https://user-images.githubusercontent.com/34352544/118668689-b7c6ef00-b7ba-11eb-9004-f771443ee098.png)
![image](https://user-images.githubusercontent.com/34352544/118668814-d0370980-b7ba-11eb-97ee-dc53efe880bf.png)

**Comment by devlemire** [comment]
That output looks solid. `players` and `playersIdsIndexed` should default to an empty Array/Object as you see in your log output. With that being said `isInQueue` should run fine and be set to `false`. But, you're seeing your app crash? That's very strange..

**Comment by devlemire** [comment]
Oh.. I see it now... you're trying to access it as `playerIdsIndexed` but the variable is called `playersIdsIndexed`

**Comment by tarolling** [comment]
......................
I want to punch a wall.
Thank you for your help.

**Comment by devlemire** [comment]
No worries. We've all been there before. Glad I could end up helping you out. Good luck with the rest of your project, I like the idea of it
