### ISSUE TITLE
createlobbyinfo

### ISSUE THREAD

**Issue by fluffykitten-oss** [devlemire/6mans-JS#13]
there is an error when creating lobby information i get the following error code.

(node:1556) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at module.exports (C:\Users\User\Desktop\TM 2v2\actions\createVoiceChannels.js:11:46)
    at module.exports (C:\Users\User\Desktop\TM 2v2\actions\createLobbyInfo.js:67:9)
    at module.exports (C:\Users\User\Desktop\TM 2v2\actions\createRandomTeams.js:34:3)
    at module.exports (C:\Users\User\Desktop\TM 2v2\actions\submitVote.js:52:7)
    at module.exports (C:\Users\User\Desktop\TM 2v2\onHandlers\message.js:94:7)
    at Client.<anonymous> (C:\Users\User\Desktop\TM 2v2\index.js:39:33)
    at Client.emit (events.js:315:20)
    at MessageCreateHandler.handle (C:\Users\User\Desktop\TM 2v2\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\User\Desktop\TM 2v2\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\User\Desktop\TM 2v2\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
(node:1556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by devlemire** [comment]
Looking into it now.

**Comment by fluffykitten-oss** [comment]
thank you :)

**Comment by devlemire** [comment]
Are you trying to modify this project as a 2v2 bot instead of 3v3?

**Comment by fluffykitten-oss** [comment]
yes

**Comment by fluffykitten-oss** [comment]
the problem im having is after everyone has voted the bot says what the team majority is and says it will Dm the teams but then breaks and i get the following error i sent you

**Comment by devlemire** [comment]
I've been looking at it for the past hour, even tried doing some code modifications to easily see if I could move the API over to a 2v2 structure. The problem you are facing is because the entire code base was written in mind with 6 players total, 3 in mind. Once you modify a single piece to be 2v2, it'll all fall apart. Everything else needs to be updated as well to be 2v2.

**Comment by devlemire** [comment]
In `actions/createVoiceChannels` modify 
```js
const parentChannel = guild.channels.find(
    channelObj => channelObj.name === process.env.categoryName && channelObj.type === 'category'
  )``` 

to be `const parentChannelID = eventObj.channel.parentID`

**Comment by fluffykitten-oss** [comment]
ok i shall thank you

**Comment by devlemire** [comment]
Shortly below that in the same file, you'll need to change 

```js
parent: parentChannel.id,
```

to

```js
parent: parentChannelID
```

**Comment by fluffykitten-oss** [comment]
i cant find const parentChanel...

**Comment by devlemire** [comment]
https://github.com/devlemire/6mans-JS/blob/b280e1eeafefe4e39490d84c1701f062abbf8699/actions/createVoiceChannels.js#L5

**Comment by fluffykitten-oss** [comment]
nvm found it

**Comment by fluffykitten-oss** [comment]
ive changed it and i have 1 error

**Comment by fluffykitten-oss** [comment]
oh nvm forgot to remove the ")"

**Comment by devlemire** [comment]
Hopefully that gets the ball moving for you, I wanted to at least offer some guidance to help out a tiny bit. But ideally, if you're taking on this project and modifying it something new, that comes with the responsibility that you are on your own.  Once your code is different than mine, it makes it harder to offer guidance cause I can't see what you see.

**Comment by fluffykitten-oss** [comment]
thank you very much for the help i was stuck and i really hope this works and sorry if i caused any inconveniences
