### ISSUE TITLE
I cannot run the command

### ISSUE THREAD

**Issue by Lectu** [devlemire/6mans-JS#4]
I followed the steps and I get stuck on "run node index.js" So far I received different error messages because I have changed some things (but that is when I saw that it wasn't working following the steps.

![error](https://user-images.githubusercontent.com/63559058/79080840-61010300-7ce6-11ea-90c0-6896da651490.png)

![image](https://user-images.githubusercontent.com/63559058/79080854-72e2a600-7ce6-11ea-9a6b-1f03ae38584a.png)

**Comment by devlemire** [comment]
Please try running the command `npm i` when you are in the `C:\Users\Owner\Desktop\Discord Bot` directory in the terminal.

`Cannot find module` means the node_modules folder is most likely missing.

**Comment by Lectu** [comment]
[image: image.png]
this is what I have following your steps

**Comment by Lectu** [comment]
[image: image.png]

**Comment by Lectu** [comment]
[image: image.png]

This is what happens after I do npm I after and still does not work.

**Comment by devlemire** [comment]
Please try re-uploading your images, they aren't loading correctly.

![image](https://user-images.githubusercontent.com/19179440/79082811-821e1f80-7cf7-11ea-9d94-f19735768fbf.png)

**Comment by Lectu** [comment]
![reupload](https://user-images.githubusercontent.com/63559058/79082832-c4476100-7cf7-11ea-82ea-ad883bdcab92.png)

Is it possible if you send me a video on how you do it. I've retried the steps about 4-5 times and I don't know. Sorry to be such a bother, I've just been trying to set this up for hours.

**Comment by devlemire** [comment]
Upon taking a closer look at your two screenshots I noticed that you have two different directories specified in the screenshots.

- C:\Users\Owner\Desktop\Discord Bot
- C:\Users\Owner\Desktop\Bot

It's very important that you are in the correct directory when running these commands or they will not work.

This new error is saying that "index.js" is not found. Which may mean you are in the wrong folder location. If you type `dir` in the console you should see `index.js` as one of the listed files.

**Comment by devlemire** [comment]
A quick trick to know where exactly you need to be is navigate to the folder using the `File Explorer` in Windows. You can then press the folder icon to the left of the file to get a copy-able location.

![image](https://user-images.githubusercontent.com/19179440/79082894-72530b00-7cf8-11ea-848d-e22e784dc148.png)

You can then go into your terminal and directly say `cd DIRECTORY` and that will take you right where you need to be in order to run the commands. Just replace `DIRECTORY` with what you copied.

**Comment by Lectu** [comment]
![image](https://user-images.githubusercontent.com/63559058/79082989-33718500-7cf9-11ea-9b24-b4d0af696bf4.png)
Ok, it's progress. Now I have this problem. It says I have entered an invalid token?

**Comment by devlemire** [comment]
So following step 2 in the README, I just download a fresh `zip` file of the latest `release`. I then <b>extracted</b> the `zip` file onto my Desktop. I then right clicked the folder and pressed `open`. I then clicked the folder icon to the left of the folder name in the top bar.

![image](https://user-images.githubusercontent.com/19179440/79082979-1ccb2e00-7cf9-11ea-929d-9d8a84897ec5.png)

I copied the directory and now I can `cd` directly to it. I then ran `npm i`

![image](https://user-images.githubusercontent.com/19179440/79082995-3bc9c000-7cf9-11ea-8815-5db3aa872c41.png)

I then created my `.env` file and added the necessary information. I now have everything I need to run it by saying `node index.js`

![image](https://user-images.githubusercontent.com/19179440/79083038-9400c200-7cf9-11ea-8f54-4a1c8c559aca.png)

**Comment by devlemire** [comment]
`invalid token` error means you didn't not create a `.env` file in the project and then added your `token` and `channelName` variables

**Comment by Lectu** [comment]
I'm doing something wrong.

![image](https://user-images.githubusercontent.com/63559058/79083203-be9f4a80-7cfa-11ea-9881-ea50766621b0.png)

![image](https://user-images.githubusercontent.com/63559058/79083207-c6f78580-7cfa-11ea-9a9e-5781b3297417.png)

![image](https://user-images.githubusercontent.com/63559058/79083216-d1b21a80-7cfa-11ea-8750-8c3b0d05e09e.png)

Could it be that I'm doing the channel name incorrectly? I tried with General at first

**Comment by Lectu** [comment]
I see the problem. I did not save it as a env file but I do not know how to save it as an env file

**Comment by devlemire** [comment]
Please notice how your `.env` was saved as `.env.txt` this makes the file not-readable by the server. When you are creating the file, you need to set the file type to `All Files`. Then you can save the file as just `.env` <b>NOT</b> `.env.txt`.

Also please be aware you just exposed your token to the internet, you should re-roll your token on discord's website `immediately`. There is a chance a bot could of scraped your token <b>already</b> and use it with malicious intentions.

**Comment by devlemire** [comment]
As for the `channelName` variable it just needs to match the spelling of your channel name in the channel list on the left side.

For example I set mine to `6mans-test-1` because that's how it is spelt there:
![image](https://user-images.githubusercontent.com/19179440/79083315-8d734a00-7cfb-11ea-8a00-efdf8575b620.png)

**Comment by Lectu** [comment]
Ok, thank you so much. I got it to work. at least it's online. But I typed !6m-help and nothing appeared. What could be the problem?

**Comment by Lectu** [comment]
I also changed the token

**Comment by Lectu** [comment]
![image](https://user-images.githubusercontent.com/63559058/79083429-4a65a680-7cfc-11ea-9703-10c4c5708d78.png)

**Comment by devlemire** [comment]
You have to type the commands in the channel you specified in `channelName`. So if it didn't work, there is a mismatch. I don't think you can use `spaces` in text channels. The bot has to be tied to a text channel.

In your most recent screenshot it looks like you are typing in `6mans` but on your last screenshot the `channelName` was set to `Rumble 6mans Test`.

<b>Please note</b> any time you change the contents of `.env`, the server needs to be restarted.

**Comment by Lectu** [comment]
I see, is it possible to add multiple text channels in the env file? If so, how do I word it

**Comment by devlemire** [comment]
With the current API only one text channel is supported.

**Comment by Lectu** [comment]
Ok, I will try to see if it'll work now.

**Comment by devlemire** [comment]
Please open another issue if problems are still occurring. I'm going to mark this issue thread as getting started issues.
