### ISSUE TITLE
Bot commands not working when I'm appearing offline

### ISSUE THREAD

**Issue by Lectu** [devlemire/6mans-JS#5]
![image](https://user-images.githubusercontent.com/63559058/79083676-b7c60700-7cfd-11ea-97c3-3390a2a61161.png)

This is inserted in the env file

![image](https://user-images.githubusercontent.com/63559058/79083706-e47a1e80-7cfd-11ea-9c01-4aa33b79f907.png)
It matches the channel name.

**Comment by Lectu** [comment]
I also, restarted the cmd and logged back in when doing this

**Comment by devlemire** [comment]
Did you download release `v1.9.1`?

**Comment by Lectu** [comment]
By that do you mean 
![image](https://user-images.githubusercontent.com/63559058/79083772-3622a900-7cfe-11ea-8b00-c35b8574f20a.png)

**Comment by devlemire** [comment]
It looks like you have `1.9.1` based on your output. If you see the bot as online and it's not responding to `!6m-help` the `.env` file might have incorrect spelling. In your case it would look like:

`channelName=queue`

Sorry if that sounds redundant, but that could be the only issue, since I just tried with a fresh install of `v1.9.1` it worked fine.

![image](https://user-images.githubusercontent.com/19179440/79083803-6ec28280-7cfe-11ea-84ef-f0765576a4bb.png)

**Comment by Lectu** [comment]
I sent a screenshot above how it looks like in the env file. Does it look incorrect?

**Comment by devlemire** [comment]
It looks correct. 

- Have you verified the bot is online in the online user's list?
- Have you verified you are on the same discord server as the discord bot?

Those are the only other things I can think of.

**Comment by Lectu** [comment]
![image](https://user-images.githubusercontent.com/63559058/79084268-cbbf3800-7d00-11ea-8e6c-52efc81219b4.png)

it is online and in the same discord as I am

**Comment by devlemire** [comment]
I'm releasing a new version of `1.9.2`, that will include a new `.env` variable called `debugLogs`.

Please add `debugLogs=true` to your existing `.env` file and copy the `.env` file to your new version of `1.9.2`. Please note you'll need to re-do the `npm i` command since this counts as the "initial setup"

**Comment by devlemire** [comment]
debugLogs will add log for what your `channelName` is set to and will also let you know if commands fail based on some conditions I've coded.

**Comment by devlemire** [comment]
https://github.com/devlemire/6mans-JS/releases/tag/1.9.2

**Comment by devlemire** [comment]
Once you are running version v1.9.2 successfully. It should log what the `channelName` is set to in the terminal. It will also log any errors that is preventing `!6m-help` from giving you an output.

**Comment by devlemire** [comment]
## Example of an Error

Here I try to direct message the bot, which is not allowed:

![image](https://user-images.githubusercontent.com/19179440/79084492-0fff0800-7d02-11ea-9ffd-77268cd96aec.png)

**Comment by devlemire** [comment]
## Example of an Error

Here I am sending a message on the <b>correct</b> channel but it is not a 6mans command:

![image](https://user-images.githubusercontent.com/19179440/79084534-548aa380-7d02-11ea-9128-8950e101cee9.png)

**Comment by devlemire** [comment]
With these new logs we can see why exactly your `!6m-help` is not being registered.

**Comment by devlemire** [comment]
@Lectu I just realized your are appearing offline. You must be <b>online</b> when interacting with the bot. This is because the bot removes players that go offline when in the queue.

**Comment by Lectu** [comment]
Wow, ok I see the problem now. It's interesting.
![image](https://user-images.githubusercontent.com/63559058/79084592-8dc31380-7d02-11ea-8117-40024f5e2f9a.png)
I appeared online and it works now. Sorry to be such a hassle but I believed you learned something because I have lol

**Comment by devlemire** [comment]
This is a design choice to prevent "malicious" players from sitting in the queue and then going offline (the queue would be effectively stuck at that point).

**Comment by devlemire** [comment]
So the bot will remove players if they are in the queue when they go offline, they will also not listen to users that are appearing offline.

**Comment by devlemire** [comment]
No worries about the hassle, this resulted in a good update to the code base to provide more information to the server owner. And we have this documented for future server owners that get stuck. Thank you for your time with the GitHub Issues process.
